import { useState } from 'react';
import { motion, ShieldCheck, Eye, EyeOff, ArrowLeft } from '../../shared/ui';
import { resetPassword } from '../../services/auth.service';
import { C } from '../../shared/runtime';

export function ResetPasswordPage({ email, otp, onBack }) {
  const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
  const submit=async e=>{e.preventDefault();setError('');if(!email||!otp){setError('Request a new verification code.');return;}if(password.length<8){setError('Password must be at least 8 characters.');return;}if(password!==confirm){setError('Passwords do not match.');return;}setLoading(true);try{await resetPassword(email,otp,password);setDone(true);}catch(err){setError(err.message||'This verification code is invalid or expired.');}finally{setLoading(false);}};
  return <div style={{minHeight:'100vh',background:'linear-gradient(135deg,#10182f,#1e2a4a 52%,#26345d)',display:'grid',placeItems:'center',padding:24,fontFamily:'Inter,system-ui,sans-serif'}}><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} style={{width:'100%',maxWidth:470,background:'#fff',borderRadius:24,padding:'38px 40px',boxShadow:'0 25px 70px rgba(0,0,0,.28)'}}><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:28}}><div style={{width:42,height:42,borderRadius:12,background:'linear-gradient(135deg,#7c3aed,#4f6ef7)',display:'grid',placeItems:'center'}}><ShieldCheck size={22} color="#fff"/></div><div><div style={{fontSize:18,fontWeight:800,color:'#111827'}}>PCA Pvt. Ltd</div><div style={{fontSize:11,color:'#9ca3af'}}>Secure password recovery</div></div></div>{done?<><div style={{fontSize:26,fontWeight:800,color:C.text}}>Password updated</div><div style={{fontSize:14,color:C.muted,lineHeight:1.6,marginTop:8}}>Your password has been changed successfully. You can now sign in with your new password.</div><button type="button" onClick={onBack} style={primary}>Back to sign in</button></>:<><div style={{fontSize:26,fontWeight:800,color:C.text}}>Create a new password</div><div style={{fontSize:14,color:C.muted,lineHeight:1.6,marginTop:7,marginBottom:24}}>Choose a strong password for your PCA Pvt. Ltd account.</div>{error&&<div style={{background:'#fff1f2',border:'1px solid #fecdd3',color:'#be123c',borderRadius:10,padding:11,fontSize:13,marginBottom:18}}>{error}</div>}<form onSubmit={submit}><label style={label}>New password</label><div style={{position:'relative',marginBottom:18}}><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} autoComplete="new-password" placeholder="At least 8 characters" style={input}/><button type="button" onClick={()=>setShow(v=>!v)} style={eye}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><label style={label}>Confirm password</label><input value={confirm} onChange={e=>setConfirm(e.target.value)} type={show?'text':'password'} autoComplete="new-password" placeholder="Re-enter your password" style={{...input,paddingLeft:14}}/><button disabled={loading} type="submit" style={primary}>{loading?'Updating…':'Update password'}</button></form><div style={{textAlign:'center',marginTop:18}}><button type="button" onClick={onBack} style={link}><ArrowLeft size={14}/> Back to sign in</button></div></>}</motion.div></div>;
}
const label={display:'block',fontSize:13,fontWeight:650,color:'#111827',marginBottom:8};
const input={width:'100%',boxSizing:'border-box',height:46,border:'1px solid #e5e7eb',borderRadius:11,padding:'0 45px 0 14px',outline:'none',fontSize:14,color:'#111827'};
const primary={width:'100%',height:48,border:0,borderRadius:11,background:'linear-gradient(135deg,#4f6ef7,#6d5dfc)',color:'#fff',fontSize:14,fontWeight:750,cursor:'pointer',marginTop:22};
const link={border:0,background:'transparent',color:'#4f6ef7',fontSize:13,fontWeight:650,cursor:'pointer',display:'inline-flex',gap:6,alignItems:'center'};
const eye={position:'absolute',right:10,top:8,width:30,height:30,border:0,background:'transparent',color:'#6b7280',cursor:'pointer'};
