// ── Framer Motion ─────────────────────────────────────────────────────────
export { motion, AnimatePresence } from "framer-motion";

// ── Lucide Icons (only the icons actually used in this app) ───────────────
// Named exports let Rollup tree-shake every unused icon at build time.
export {
  LayoutDashboard,
  GraduationCap,
  Users,
  BookOpen,
  ClipboardCheck,
  ListChecks,
  Megaphone,
  DollarSign,
  UserCircle,
  LogOut,
  Bell,
  Search,
  ChevronDown,
  Calendar,
  TrendingUp,
  Star,
  AlertTriangle,
  Eye,
  EyeOff,
  LockKeyhole,
  Trash2,
  Edit,
  Plus,
  X,
  Check,
  Copy,
  Clock,
  BarChart2,
  Award,
  Briefcase,
  Mail,
  Phone,
  Shield,
  ShieldCheck,
  CheckCircle2,
  ArrowLeft,
  Menu,
  CheckSquare,
  Settings as Settings2,
  Home,
  School,
  Layers,
  DoorOpen,
  Sun,
  Moon,
  Download,
} from "lucide-react";

// ── Recharts (only chart primitives used across pages) ────────────────────
export {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  LineChart,
  Line,
  Legend,
  AreaChart,
  Area,
} from "recharts";
