import { useEffect, useState } from "react";
import { motion, Plus, Search, School } from "../../shared/ui";
import { C } from "../../shared/runtime";
import { list, create, update, remove } from "../../services/resource.service";
import { api } from "../../services/apiClient";
import { onResourceChange } from "../../services/socket.service";
import { AdminClassModal } from "../../components/classes/AdminClassModal";
import { AdminClassCards, EmptyClassState } from "../../components/classes/AdminClassCards";
import { AdminClassForm } from "../../components/classes/AdminClassForm";

const blankClass = { name: "", section: "", capacity: 100, room: "", subjectTeacher: "", classTeacher: "", status: "active" };
const gradeOrder = item => { const source = String(item.gradeLevel || item.name || "").toLowerCase(); if (source.includes("nursery")) return 0; if (source.includes("lkg")) return 1; if (source.includes("ukg")) return 2; const match = source.match(/\d+/); return match ? Number(match[0]) + 3 : 999; };
const sortClasses = items => [...items].sort((a, b) => gradeOrder(a) - gradeOrder(b) || String(a.section || "").localeCompare(String(b.section || ""), undefined, { numeric: true }) || String(a.name || "").localeCompare(String(b.name || ""), undefined, { numeric: true }));

export function AdminClasses() {
  const [classes, setClasses] = useState([]), [search, setSearch] = useState(""), [showAdd, setShowAdd] = useState(false), [addForm, setAddForm] = useState(blankClass), [editingId, setEditingId] = useState(null), [editForm, setEditForm] = useState({}), [saved, setSaved] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [registeredStudents, setRegisteredStudents] = useState([]), [registeredSubjects, setRegisteredSubjects] = useState([]), [registeredTeachers, setRegisteredTeachers] = useState([]), [selectedStudentIds, setSelectedStudentIds] = useState([]), [selectedSubjectIds, setSelectedSubjectIds] = useState([]), [loadingRegistrations, setLoadingRegistrations] = useState(false);
  const loadData = () => { setLoading(true); list("classes", "limit=100").then(result => { setClasses(sortClasses(result.data || result || [])); setError(""); }).catch(err => setError(err.message || "Unable to load classes")).finally(() => setLoading(false)); };
  useEffect(() => { loadData(); const unsubscribe = onResourceChange("classes", loadData); return () => unsubscribe?.(); }, []);
  const filtered = classes.filter(item => { const query = search.toLowerCase(); return [item.name, item.section, item.gradeLevel, item.room, item.subjectTeacher].some(value => String(value || "").toLowerCase().includes(query)); });
  const loadRegistrationOptions = async classId => { setLoadingRegistrations(true); try { const [studentResponse, subjectResponse, staffResponse] = await Promise.all([list("students", "status=active&limit=500"), list("subjects", "limit=100"), list("staff", "limit=100")]); const students = studentResponse.data || studentResponse || [], subjects = subjectResponse.data || subjectResponse || [], staff = staffResponse.data || staffResponse || []; setRegisteredStudents(Array.isArray(students) ? students : []); setRegisteredSubjects(Array.isArray(subjects) ? subjects : []); setRegisteredTeachers(Array.isArray(staff) ? staff : []); if (classId) { setSelectedStudentIds(students.filter(item => String(item.classId?._id || item.classId) === String(classId)).map(item => String(item._id || item.id))); setSelectedSubjectIds(subjects.filter(item => (item.classIds || []).some(id => String(id?._id || id) === String(classId))).map(item => String(item._id || item.id))); } } catch (err) { setRegisteredStudents([]); setRegisteredSubjects([]); setRegisteredTeachers([]); setSelectedStudentIds([]); setSelectedSubjectIds([]); throw err; } finally { setLoadingRegistrations(false); } };
  const openAddModal = async () => { setShowAdd(true); setError(""); setAddForm({ ...blankClass }); setSelectedStudentIds([]); setSelectedSubjectIds([]); try { await loadRegistrationOptions(); } catch (err) { setError(err.message || "Unable to load registration options"); } };
  const resourceId = result => result?._id || result?.id || result?.data?._id || result?.data?.id || result?.data?.data?._id || result?.data?.data?.id;
  const assignSubjects = async (classId, subjectIds) => { const selected = new Set(subjectIds.map(String)); await Promise.all(registeredSubjects.map(subject => { const id = String(subject._id || subject.id), current = (subject.classIds || []).map(item => item?._id || item).filter(Boolean); if (!selected.has(id) || current.some(value => String(value) === String(classId))) return null; return api.patch(`/subjects/${id}`, { classIds: [...new Set([...current, classId])] }); })); };
  const handleAdd = async () => { if (saving) return; if (!addForm.name.trim()) return setError("Class Name is required"); setSaving(true); setError(""); try { const result = await create("classes", { name: addForm.name.trim(), section: addForm.section.trim(), capacity: Number(addForm.capacity) || 40, room: addForm.room.trim(), subjectTeacher: addForm.subjectTeacher?.trim() || "", classTeacher: addForm.classTeacher || undefined, status: addForm.status || "active" }); const id = resourceId(result); if (!id) throw new Error("Class ID was not returned"); if (selectedStudentIds.length) await api.patch("/students/assign-class", { classId: id, studentIds: selectedStudentIds }); await assignSubjects(id, selectedSubjectIds); setShowAdd(false); setAddForm({ ...blankClass }); loadData(); } catch (err) { setError(err.message || "Failed to create class"); } finally { setSaving(false); } };
  const handleEdit = item => { const id = item._id || item.id; setEditingId(id); setSaved(false); setEditForm({ name: item.name || "", section: item.section || "", capacity: item.capacity || 40, room: item.room || "", subjectTeacher: item.subjectTeacher || "", classTeacher: item.classTeacher?._id || item.classTeacher || "", status: item.status || "active" }); setSelectedStudentIds([]); setSelectedSubjectIds([]); loadRegistrationOptions(id).catch(err => setError(err.message || "Unable to load registration options")); };
  const handleSaveEdit = async () => { if (saving) return; if (!editForm.name?.trim()) return setError("Class Name is required"); setSaving(true); setError(""); try { await update("classes", editingId, { name: editForm.name.trim(), section: editForm.section.trim(), capacity: Number(editForm.capacity) || 100, room: editForm.room.trim(), subjectTeacher: editForm.subjectTeacher?.trim() || "", classTeacher: editForm.classTeacher || undefined, status: editForm.status || "active" }); await api.patch("/students/assign-class", { classId: editingId, studentIds: selectedStudentIds }); await Promise.all(registeredSubjects.map(subject => { const current = (subject.classIds || []).map(item => item?._id || item).filter(id => String(id) !== String(editingId)); const next = selectedSubjectIds.includes(String(subject._id)) ? [...current, editingId] : current; return api.patch(`/subjects/${subject._id}`, { classIds: next }); })); setSaved(true); setTimeout(() => { setEditingId(null); setSaved(false); loadData(); }, 900); } catch (err) { setError(err.message || "Failed to save class"); } finally { setSaving(false); } };
  const handleDelete = async id => { const target = classes.find(item => String(item._id || item.id) === String(id)); if (!window.confirm(`Are you sure you want to delete class "${target?.name || "this class"}"?`)) return; try { await remove("classes", id); setClasses(previous => previous.filter(item => String(item._id || item.id) !== String(id))); } catch (err) { setError(err.message || "Failed to delete class"); } };
  const formProps = (form, setForm, edit = false) => ({ form, setForm, teachers: registeredTeachers, students: registeredStudents, subjects: registeredSubjects, selectedStudentIds, setSelectedStudentIds, selectedSubjectIds, setSelectedSubjectIds, loading: loadingRegistrations, onCancel: () => edit ? setEditingId(null) : setShowAdd(false), onSubmit: edit ? handleSaveEdit : handleAdd, saving, edit, saved });
  return <div style={{ padding: 28, display: "flex", flexDirection: "column", gap: 24, background: "linear-gradient(135deg, #f4f7ff 0%, #f8fafc 55%, #fff7ed 100%)" }}>
    <div style={{ background: "linear-gradient(135deg, #ffffff 0%, #eef2ff 100%)", borderRadius: 16, padding: 24, border: "1px solid #dbe4ff", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 16 }}><div style={{ display: "flex", alignItems: "center", gap: 14 }}><School size={26} color={C.accent} /><div><div style={{ fontSize: 20, fontWeight: 800, color: "#172554" }}>Classes & Sections</div><div style={{ fontSize: 12.5, color: "#475569", marginTop: 3 }}>{classes.length} Total {classes.length === 1 ? "Class" : "Classes"} registered</div></div></div><div style={{ display: "flex", alignItems: "center", gap: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 8, background: "#fff", border: "1px solid #cbd5e1", borderRadius: 10, padding: "8px 14px", width: 240 }}><Search size={14} color={C.muted} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search classes..." style={{ border: "none", background: "transparent", outline: "none", fontSize: 13, width: "100%" }} /></div><motion.button type="button" onClick={openAddModal} style={{ display: "flex", alignItems: "center", gap: 6, background: C.accent, color: "#fff", border: "none", borderRadius: 10, padding: "9px 18px", cursor: "pointer", fontSize: 13, fontWeight: 600 }}><Plus size={15} />Add Class</motion.button></div></div>
    {error && <div style={{ background: "#fff1f2", color: "#be123c", border: "1px solid #fecdd3", padding: "12px 16px", borderRadius: 10, fontSize: 13, fontWeight: 600 }}>{error}</div>}
    {loading ? <div style={{ background: C.white, borderRadius: 16, padding: 60, textAlign: "center", color: C.muted }}>Loading classes...</div> : filtered.length ? <AdminClassCards classes={filtered} onEdit={handleEdit} onDelete={handleDelete} /> : <EmptyClassState search={search} onCreate={openAddModal} />}
    {showAdd && <AdminClassModal title="Add New Class" onClose={() => setShowAdd(false)}><AdminClassForm {...formProps(addForm, setAddForm)} /></AdminClassModal>}
    {editingId && <AdminClassModal title="Edit Class" onClose={() => setEditingId(null)}><AdminClassForm {...formProps(editForm, setEditForm, true)} /></AdminClassModal>}
  </div>;
}
